// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Forum.Models;

public partial class Thread
{
    public int ThreadId { get; set; }

    public int Opid { get; set; }

    public string Title { get; set; }

    public int TopicId { get; set; }

    public virtual Post Op { get; set; }

    public virtual Topic Topic { get; set; }

    public virtual ICollection<User> User { get; set; } = new List<User>();
}